services:
  mongo_db:
    image: mongo:7.0
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongoDB:/data/db

  redis_cache:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://mongo_db:27017
      REDIS: redis://redis_cache:6379
    depends_on:
      - mongo_db
      - redis_cache
    command: sh -c 'if [ "$NODE_ENV" = "production" ]; then pnpm start; else pnpm dev; fi'
    volumes:
      - .:/usr/src/app

  nginx:
    image: nginx:1.24.0
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 5000:5000

volumes:
  mongoDB: {}
