services:
  # Mongodb
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongoDB:/data/db

  redis_cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      MONGODB_URL: mongodb://mongo_db:27017
      REDIS: redis://redis_cache:6379
    depends_on:
      - mongo_db
      - redis_cache
    command: pnpm dev
    volumes:
      - .:/usr/src/app

volumes:
  mongoDB: {}
